server:
  port: 8886  #服务器端口配置
  servlet:
    session:
      timeout: 21600   #session过期时间配置


#注册中心配置
eureka:
  client:
    service-url:
      defaultZone: http://192.168.11.26:9001/eureka/
  instance:
    instance-id: springcloud-provider
    prefer-ip-address: true

spring:
  application:
    name: springcloud-provider #应用名配置
  datasource:          #数据源配置
    druid:
      first:
        type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&allowMultiQueries=true
            name: root
            password: 123456
      second:
        type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://localhost:3306/test2?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&allowMultiQueries=true
            name: root
            password: 123456
      initial-size: 10              # 初始化大小
          max-active: 100           # 最小
          min-idle: 10              # 最大
          max-wait: 60000           # 配置获取连接等待超时的时间
          pool-prepared-statements: true  # 打开PSCache
          max-pool-prepared-statement-per-connection-size: 20  #指定每个连接上PSCache的大小
          time-between-eviction-runs-millis: 60000
          min-evictable-idle-time-millis: 300000
          #Oracle需要打开注释
          #validation-query: SELECT 1 FROM DUAL
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          stat-view-servlet:
              enabled: true
              url-pattern: /druid/*
              #login-username: admin
              #login-password: admin
          filter:
              stat:
                  log-slow-sql: true
                  slow-sql-millis: 1000
                  merge-sql: false
              wall:
                  config:
                      multi-statement-allow: true
  redis:
    host: localhost
    password: #redis密码，默认为空
    pool:
      max-active: 200
      max-idle: 100
      max-wait: 5000
      min-idle: 0
    port: 6379
    read-timeout: 5000
    timeout: 5000
